package scan;


import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import static scan.Application.scanPanel;



public final class ScanPanel extends JInternalFrame {

    
    public static Thumb[] thumbs = new Thumb[3];
    
    
    public static Preview preview;
    
    
    public static ScanPanel instance;
    
    public double gamma = 0.0f;
    public java.lang.Integer evRed = 0;
    public java.lang.Integer evGreen = 0;
    public java.lang.Integer evBlue = 0;
    
    
    
    private final int thumbSize = 160;        // 186 - 15
    
    private final int previewSize = 427;      // 427 = 1494 / 3,5
    private final int previewBorder = 6;
    
    
    
    public ScanPanel() 
    {
         
        initComponents();
          
        
        instance = this;
        
        
        this.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e)
            {
                scan.Application.scannerButton.setEnabled(true);
                scanPanel.setVisible(false);
            }        
        });
        
        
        
        
        thumbs[0] = new Thumb(0, thumbSize, thumbSize);        
        thumbs[0].setBounds(10, 10, thumbs[0].width, thumbs[0].height);
        
        thumbs[1] = new Thumb(1, thumbSize, thumbSize);        
        thumbs[1].setBounds(10, 10 + thumbs[0].height + 10, thumbs[1].width, thumbs[1].height);
        
        thumbs[2] = new Thumb(2, thumbSize, thumbSize);        
        thumbs[2].setBounds(10, 10 + thumbs[0].height + 10 + thumbs[1].height + 10, thumbs[2].width, thumbs[2].height);

        
        
        add(thumbs[0]);
        add(thumbs[1]);
        add(thumbs[2]);
        
                 
            
        preview = new Preview(previewSize, previewBorder);        
        preview.setBounds(thumbs[0].width + 20, 10, previewSize + (2*previewBorder), previewSize + (2*previewBorder));  

        add(preview);
        
        
        this.setBounds(230, 190, thumbs[0].width + previewSize + (2*previewBorder) + 37, 3*(thumbs[0].height + 10) + 40);


        
        DetectDevice detectDevice = new DetectDevice(false);
           
            
    }
    
    
        
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThumbButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonPreview = new javax.swing.JButton();
        jButtonScan = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(800, 800));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        ThumbButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ThumbButton.setText("Thumbs");
        ThumbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThumbsActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton2.setText("Split");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonPreview.setText("Preview");
        jButtonPreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPreviewClicked(evt);
            }
        });

        jButtonScan.setText("Scan");
        jButtonScan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonScanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(ThumbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonScan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(728, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThumbButton)
                    .addComponent(jButton2)
                    .addComponent(jButtonPreview)
                    .addComponent(jButtonScan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThumbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThumbsActionPerformed
        
        Thumbs doThumbs;
        
        if (scan.DetectDevice.device != null)
            if (scan.DetectDevice.device instanceof String)
                if (scan.DetectDevice.device.contains("/dev/sg"))
                    doThumbs = new Thumbs(scan.DetectDevice.device);
        
    }//GEN-LAST:event_ThumbsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Split split;
            
        split = new Split();
        split.doSplit();
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPreviewClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPreviewClicked
        
        Previews view;
        
        if (scan.DetectDevice.device != null)
            if (scan.DetectDevice.device instanceof String)
                if (scan.DetectDevice.device.contains("/dev/sg"))
                    view = new Previews(scan.DetectDevice.device);
        
    }//GEN-LAST:event_jButtonPreviewClicked

    private void jButtonScanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonScanMouseClicked
        
        if (gamma > 0.0f)
        {
            Evs ev = new Evs(gamma, evRed, evGreen, evBlue);
        }
        
    }//GEN-LAST:event_jButtonScanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ThumbButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPreview;
    private javax.swing.JButton jButtonScan;
    // End of variables declaration//GEN-END:variables


}
